version: '3.1'

services:
  mongo:
    image: mongo
    # defining a custom container name.
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # assigning a network for this container.
    networks:
      - mongodb_network
  mongo-express:
    image: mongo-express
    # defining a custom container name.
    container_name: mongodbexpress
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    # assigning a network for this container.
    networks:
      - mongodb_network
networks: 
  # defining the mongodb_network
  mongodb_network: 
    name: mongodb_network      